/**
 * @file llms.ts
 * @description 生成llms.txt文件，用于告知大语言模型网站的结构和内容
 */

import { getBlogPosts, getBlogTags } from '@/lib/blog'
import { getProductData } from '@/lib/products'
//import { MetadataRoute } from 'next'

export default async function llms(): Promise<string> {
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://www.dkgasspring.com'

  try {
    // 获取所有语言的数据
    const languages = ['zh', 'en', 'es', 'de']
    const posts = await Promise.all(languages.map(lang => getBlogPosts(lang as "zh" | "en" | "es" | "de")))
    const tags = await Promise.all(languages.map(lang => getBlogTags(lang as "zh" | "en" | "es" | "de")))
    const products = await Promise.all(languages.map(lang => getProductData(lang as "zh" | "en" | "es" | "de")))

    // 构建llms.txt内容
    const content = [
      '# Website Structure and Content Guide for LLMs',
      '',
      '## Available Languages',
      'zh - Chinese',
      'en - English',
      'es - Spanish',
      'de - German',
      '',
      '## Main Pages',
      `${baseUrl}/ - Homepage`,
      `${baseUrl}/products - Products Overview`,
      `${baseUrl}/applications - Applications Overview`,
      `${baseUrl}/blog - Blog Posts`,
      `${baseUrl}/contact - Contact Information`,
      '',
      '## Content Structure',
      '1. Products',
      ...languages.flatMap((lang, i) => [
        `   ${lang.toUpperCase()} Categories:`,
        ...products[i].categories.map(cat => `   - ${cat.id}: ${cat.title}`)
      ]),
      '',
      '2. Blog Posts',
      ...languages.flatMap((lang, i) => [
        `   ${lang.toUpperCase()} Posts:`,
        ...posts[i].map(post => `   - ${post.title} (${post.date})`)
      ]),
      '',
      '3. Blog Tags',
      ...languages.flatMap((lang, i) => [
        `   ${lang.toUpperCase()} Tags:`,
        ...tags[i].map(tag => `   - ${tag}`)
      ]),
      '',
      '## Update Frequency',
      '- Homepage: Weekly',
      '- Products: Weekly',
      '- Applications: Monthly',
      '- Blog: Daily',
      '- Contact: Monthly',
      '',
      '## Note',
      'This file is automatically generated to help language models better understand the website structure.'
    ].join('\n')

    return content
  } catch (error) {
    console.error('Error generating llms.txt:', error)
    // 返回基本信息
    return [
      '# Website Structure',
      '',
      '## Main Pages',
      `${baseUrl}/ - Homepage`,
      `${baseUrl}/products - Products`,
      `${baseUrl}/applications - Applications`,
      `${baseUrl}/blog - Blog`,
      `${baseUrl}/contact - Contact`,
      '',
      '## Note',
      'Error occurred while generating full content.'
    ].join('\n')
  }
}